### ISSUE TITLE
Applying the model on other satellite imagery

### ISSUE THREAD

**Issue by wxyang007** [DarthReca/depth-any-canopy#3]
Thank you for sharing the repo and the cool work! I'm wondering if the model can be applied on other sources of satellite imagery, for example data with coarser spatial resolution and/or more spectral bands such as Landsat. If so, are there any steps in general I should take before applying the model? Many thanks!

**Comment by DarthReca** [comment]
The models are based on Depth Anything V2 with relative depths. You could try to start from my finetuning or their pretraining. In theory, the model could be applied to different bands, but the issue is the initial pre-training was done on RGB. I cannot say if they can generalize well in the hyperspectral domain.

**Comment by wxyang007** [comment]
This is helpful to know! Many thanks for the information!
